version: '3.4'
services:
  coord:
    build:
      context: .
      dockerfile: Dockerfile.coord
    container_name: coord
    image: coord:coord-latest
    ports:
      - '56837:56837'
      - '59141:59141'
    networks:
      - bagel
  worker0:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker0
    image: worker0:worker0-latest
    depends_on:
      - coord
    command: "0"
    ports:
      - '55505:55505'
      - '59061:59061'
      - '65116:65116'
    networks:
      - bagel
  worker1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker1
    image: worker1:worker1-latest
    depends_on:
      - coord
      - worker0
    command: "1"
    ports:
      - '63517:63517'
      - '55328:55328'
      - '52205:52205'
    networks:
      - bagel


networks:
  bagel:
    driver: bridge